--- Country, Name ---
insert into Country values(0, "Portugal");
insert into Country values(1, "Spain");
insert into Country values(2, "France");
insert into Country values(3, "Germany");
insert into Country values(4, "Netherlands");
insert into Country values(5, "Belgium");
insert into Country values(6, "United Kingdom");
insert into Country values(7, "Italy");
insert into Country values(8, "Austria");
insert into Country values(9, "Denmark");
insert into Country values(10, "Norway");
insert into Country values(11, "Sweden");
insert into Country values(12, "Finland");
insert into Country values(13, "Switzerland");
insert into Country values(14, "Greece");
insert into Country values(15, "United States of America");
insert into Country values(16, "Canada");
insert into Country values(17, "Brazil");
insert into Country values(18, "Morocco");
insert into Country values(19, "India");
insert into Country values(20, "China");
insert into Country values(21, "Japan");
insert into Country values(22, "Russia");
insert into Country values(23, "United Arab Emirates");

--- City, Country, Name ---
insert into City values(00, 00, "Lisbon");
insert into City values(01, 01, "Madrid");
insert into City values(02, 02, "Paris");
insert into City values(03, 03, "Berlin");
insert into City values(04, 04, "Amsterdam");
insert into City values(05, 05, "Brussels");
insert into City values(06, 06, "London");
insert into City values(07, 07, "Rome");
insert into City values(08, 08, "Prague");
insert into City values(09, 09, "Copenhagen");
insert into City values(10, 10, "Oslo");
insert into City values(11, 11, "Stockholm");
insert into City values(12, 12, "Helsinki");
insert into City values(13, 13, "Bern");
insert into City values(14, 14, "Athens");
insert into City values(15, 15, "New York");
insert into City values(16, 16, "Toronto");
insert into City values(17, 17, "Brasilia");
insert into City values(18, 18, "Casablanca");
insert into City values(19, 19, "New Delhi");
insert into City values(20, 20, "Beijing");
insert into City values(21, 21, "Tokyo");
insert into City values(22, 22, "Moscow");
insert into City values(23, 23, "Dubai");
insert into City values(24, 00, "Oporto");
insert into City values(25, 03, "Frankfurt");
insert into City values(26, 13, "Geneva");
insert into City values(27, 02, "Barcelona");

--- Airport, City, Name, Code ---
insert into Airport values(00, 00, "Lisbon Portela Airport", "LIS");
insert into Airport values(01, 01, "Madrid-Barajas Adolfo Suarez", "MAD");
insert into Airport values(02, 02, "Charles de Gaulle", "CDG");
insert into Airport values(03, 03, "Berlin Brandenburg", "BER");
insert into Airport values(04, 04, "Amsterdam Airport Schiphol", "AMS");
insert into Airport values(05, 05, "Brussels Airport", "BRU");
insert into Airport values(06, 06, "London City Airport", "LCY");
insert into Airport values(07, 07, "Leonardo da Vinci International", "FCO");
insert into Airport values(08, 08, "Václav Havel", "PRG");
insert into Airport values(09, 09, "Copenhagen Airport", "CPH");
insert into Airport values(10, 10, "Oslo Airport", "OSL");
insert into Airport values(11, 11, "Stockholm Arlanda", "ARN");
insert into Airport values(12, 12, "Helsinki Airport", "HEL");
insert into Airport values(13, 13, "Bern Airport", "BRN");
insert into Airport values(14, 14, "Athens International", "ATH");
insert into Airport values(15, 15, "John F. Kennedy", "JFK");
insert into Airport values(16, 16, "Toronto Pearson", "YYZ");
insert into Airport values(17, 17, "International Airport of Brasilia", "BSB");
insert into Airport values(18, 18, "Mohammed V", "CMN");
insert into Airport values(19, 19, "Indira Gandhi", "DEL");
insert into Airport values(20, 20, "Beijing Capital", "PEK");
insert into Airport values(21, 21, "Haneda", "HND");
insert into Airport values(22, 22, "Vnukovo", "VKO");
insert into Airport values(23, 23, "Dubai International Airport", "DXB");
insert into Airport values(24, 24, "Francisco Sa Carneiro", "OPO");
insert into Airport values(25, 25, "Frankfurt Airport", "FRA");
insert into Airport values(26, 26, "Geneve Airport", "GVA");
insert into Airport values(27, 27, "Barcelona–El Prat", "BCN");
insert into Airport values(28, 06, "St Pancras International", "QQS");
insert into Airport values(29, 15, "LaGuardia", "LGA");
insert into Airport values(30, 15, "Newark Liberty", "EWR");
